inherit_from:
  - .rubocop_todo.yml

AsciiComments:
  Enabled: false

Lambda:
  Enabled: false

ClassAndModuleChildren:
  Enabled: false

AccessorMethodName:
  Enabled: false

Documentation:
  Enabled: false

AndOr:
  Enabled: false

AllCops:
  Exclude:
    - 'spec/i18n_spec.rb'

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - config/environments/*

Lint/UselessAssignment:
  Exclude:
    - spec/**/*

Layout/SpaceAroundMethodCallOperator:
  Enabled: false

Lint/RaiseException:
  Enabled: false

Lint/StructNewOverride:
  Enabled: false

Style/ExponentialNotation:
  Enabled: false

Style/HashEachMethods:
  Enabled: false

Style/HashTransformKeys:
  Enabled: false

Style/HashTransformValues:
  Enabled: false

AllCops:
  Exclude:
    - db/**/*
    - config/initializers/*
    - config/unicorn.rb
    - config/unicorn_staging.rb
    - tmp/**/*
    - node_modules/**/*
    - vendor/**/*
    - "bin/*"
