version: "3"
services:
  db:
    image: postgres:11.0-alpine
    volumes:
      - datavol:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  web:
    build:
      context: .
      dockerfile: Dockerfile.production
    environment:
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      RAILS_ENV: test
    volumes:
      - .:/app
    env_file: .env.test
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  datavol:
